In [5]:
import pandas as pd

employee_df = pd.read_csv(r"C:\Users\dell\Downloads\Employee.csv") 
performance_rating_df = pd.read_csv(r"C:\Users\dell\Downloads\PerformanceRating.csv") 

print("Employee Data:")
print(employee_df.head())
print("\nPerformance Rating Data:")
print(performance_rating_df.head())

Employee Data:
  EmployeeID   FirstName LastName      Gender  Age BusinessTravel  \
0  3012-1A41    Leonelle    Simco      Female   30    Some Travel
1  CBCB-9C9D     Leonerd    Aland        Male   38    Some Travel
2  95D7-1CE9       Ahmed    Sykes        Male   43    Some Travel
3  47A0-559B  Ermentrude   Berrie  Non-Binary   39    Some Travel
4  42CC-040A       Stace   Savege      Female   29    Some Travel

        Department  DistanceFromHome (KM) State                Ethnicity  ...  \
0            Sales                     27    IL                    White  ...
1            Sales                     23    CA                    White  ...
2  Human Resources                     29    CA  Asian or Asian American  ...
3       Technology                     12    IL                    White  ...
4  Human Resources                     29    CA                    White  ...

   MaritalStatus  Salary StockOptionLevel OverTime    HireDate  Attrition  \
0       Divorced  102059                1       No  2012-01-03         No
1         Single  157718                0      Yes  2012-01-04         No
2        Married  309964                1       No  2012-01-04         No
3        Married  293132                0       No  2012-01-05         No
4         Single   49606                0       No  2012-01-05        Yes

  YearsAtCompany YearsInMostRecentRole YearsSinceLastPromotion  \
0             10                     4                       9
1             10                     6                      10
2             10                     6                      10
3             10                    10                      10
4              6                     1                       1

   YearsWithCurrManager
0                     7
1                     0
2                     8
3                     0
4                     6

[5 rows x 23 columns]

Performance Rating Data:
  PerformanceID EmployeeID ReviewDate  EnvironmentSatisfaction  \
0          PR01  79F7-78EC   1/2/2013                        5
1          PR02  B61E-0F26   1/3/2013                        5
2          PR03  F5E3-48BB   1/3/2013                        3
3          PR04  0678-748A   1/4/2013                        5
4          PR05  541F-3E19   1/4/2013                        5

   JobSatisfaction  RelationshipSatisfaction  TrainingOpportunitiesWithinYear  \
0                4                         5                                1
1                4                         4                                1
2                4                         5                                3
3                3                         2                                2
4                2                         3                                1

   TrainingOpportunitiesTaken  WorkLifeBalance  SelfRating  ManagerRating
0                           0                4           4              4
1                           3                4           4              3
2                           2                3           5              4
3                           0                2           3              2
4                           0                4           4              3

In [8]:
print("أول 5 صفوف من جدول Employee:")
print(employee_df.head())
print("\nمعلومات عامة عن الجدول:")
print(employee_df.info())
print("\nإحصائيات أساسية:")
print(employee_df.describe())

print("\nعدد القيم المفقودة في كل عمود:")
print(employee_df.isnull().sum())
print("\nنسبة القيم المفقودة في كل عمود:")
print(employee_df.isnull().mean() * 100)

if employee_df['BusinessTravel'].isnull().sum() > 0:
    employee_df['BusinessTravel'].fillna('Non-Travel', inplace=True)
if employee_df['Salary'].isnull().sum() > 0:
    employee_df['Salary'].fillna(employee_df['Salary'].mean(), inplace=True)
if employee_df['EmployeeID'].isnull().sum() > 0:
    employee_df.dropna(subset=['EmployeeID'], inplace=True)
print("\nعدد القيم المفقودة بعد المعالجة:")
print(employee_df.isnull().sum())

duplicates = employee_df.duplicated(subset=['EmployeeID']).sum()
print(f"\nعدد الصفوف المكررة بناءً على EmployeeID: {duplicates}")
if duplicates > 0:
    employee_df.drop_duplicates(subset=['EmployeeID'], keep='first', inplace=True)
    print("تم حذف الصفوف المكررة.")
print(f"عدد الصفوف بعد حذف التكرارات: {len(employee_df)}")

print("\nأنواع البيانات لكل عمود:")
print(employee_df.dtypes)
employee_df['HireDate'] = pd.to_datetime(employee_df['HireDate'], errors='coerce')
employee_df['Age'] = pd.to_numeric(employee_df['Age'], errors='coerce')
employee_df['Salary'] = pd.to_numeric(employee_df['Salary'], errors='coerce')
employee_df['Gender'] = employee_df['Gender'].astype(str)
employee_df['MaritalStatus'] = employee_df['MaritalStatus'].astype(str)
print("\nأنواع البيانات بعد التحويل:")
print(employee_df.dtypes)

print("\nإحصائيات Age:")
print(employee_df['Age'].describe())
outliers_age = employee_df[(employee_df['Age'] < 18) | (employee_df['Age'] > 100)]
print(f"عدد القيم الشاذة في Age: {len(outliers_age)}")
employee_df = employee_df[(employee_df['Age'] >= 18) & (employee_df['Age'] <= 100)]

print("\nإحصائيات Salary:")
print(employee_df['Salary'].describe())
outliers_salary = employee_df[(employee_df['Salary'] <= 0) | (employee_df['Salary'] > 1_000_000)]
print(f"عدد القيم الشاذة في Salary: {len(outliers_salary)}")
employee_df = employee_df[(employee_df['Salary'] > 0) & (employee_df['Salary'] <= 1_000_000)]

print("\nالقيم الفريدة في Gender:")
print(employee_df['Gender'].unique())
employee_df['Gender'] = employee_df['Gender'].str.lower().str.strip()
employee_df['Gender'] = employee_df['Gender'].replace({'m': 'male', 'f': 'female'})
print("القيم الفريدة في Gender بعد التنظيف:")
print(employee_df['Gender'].unique())

print("\nالقيم الفريدة في MaritalStatus:")
print(employee_df['MaritalStatus'].unique())
employee_df['MaritalStatus'] = employee_df['MaritalStatus'].str.lower().str.strip()
employee_df['MaritalStatus'] = employee_df['MaritalStatus'].replace({'single': 'single', 'married': 'married', 'divorced': 'divorced'})
print("القيم الفريدة في MaritalStatus بعد التنظيف:")
print(employee_df['MaritalStatus'].unique())

print("\nالقيم الفريدة في Department:")
print(employee_df['Department'].unique())
employee_df['Department'] = employee_df['Department'].str.lower().str.strip()

print("\nالقيم الفريدة في JobRole:")
print(employee_df['JobRole'].unique())
employee_df['JobRole'] = employee_df['JobRole'].str.lower().str.strip()

print("\nالقيم الفريدة في Education:")
print(employee_df['Education'].unique())
employee_df['Education'] = employee_df['Education'].astype(int)

employee_df.to_csv('employee_cleaned.csv', index=False)
print("\nتم حفظ الجدول بعد التنظيف باسم employee_cleaned.csv")

أول 5 صفوف من جدول Employee:
  EmployeeID   FirstName LastName      Gender  Age BusinessTravel  \
0  3012-1A41    Leonelle    Simco      Female   30    Some Travel
1  CBCB-9C9D     Leonerd    Aland        Male   38    Some Travel
2  95D7-1CE9       Ahmed    Sykes        Male   43    Some Travel
3  47A0-559B  Ermentrude   Berrie  Non-Binary   39    Some Travel
4  42CC-040A       Stace   Savege      Female   29    Some Travel

        Department  DistanceFromHome (KM) State                Ethnicity  ...  \
0            Sales                     27    IL                    White  ...
1            Sales                     23    CA                    White  ...
2  Human Resources                     29    CA  Asian or Asian American  ...
3       Technology                     12    IL                    White  ...
4  Human Resources                     29    CA                    White  ...

   MaritalStatus  Salary StockOptionLevel OverTime    HireDate  Attrition  \
0       Divorced  102059                1       No  2012-01-03         No
1         Single  157718                0      Yes  2012-01-04         No
2        Married  309964                1       No  2012-01-04         No
3        Married  293132                0       No  2012-01-05         No
4         Single   49606                0       No  2012-01-05        Yes

  YearsAtCompany YearsInMostRecentRole YearsSinceLastPromotion  \
0             10                     4                       9
1             10                     6                      10
2             10                     6                      10
3             10                    10                      10
4              6                     1                       1

   YearsWithCurrManager
0                     7
1                     0
2                     8
3                     0
4                     6

[5 rows x 23 columns]

معلومات عامة عن الجدول:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   EmployeeID               1470 non-null   object
 1   FirstName                1470 non-null   object
 2   LastName                 1470 non-null   object
 3   Gender                   1470 non-null   object
 4   Age                      1470 non-null   int64
 5   BusinessTravel           1470 non-null   object
 6   Department               1470 non-null   object
 7   DistanceFromHome (KM)    1470 non-null   int64
 8   State                    1470 non-null   object
 9   Ethnicity                1470 non-null   object
 10  Education                1470 non-null   int64
 11  EducationField           1470 non-null   object
 12  JobRole                  1470 non-null   object
 13  MaritalStatus            1470 non-null   object
 14  Salary                   1470 non-null   int64
 15  StockOptionLevel         1470 non-null   int64
 16  OverTime                 1470 non-null   object
 17  HireDate                 1470 non-null   object
 18  Attrition                1470 non-null   object
 19  YearsAtCompany           1470 non-null   int64
 20  YearsInMostRecentRole    1470 non-null   int64
 21  YearsSinceLastPromotion  1470 non-null   int64
 22  YearsWithCurrManager     1470 non-null   int64
dtypes: int64(9), object(14)
memory usage: 264.3+ KB
None

إحصائيات أساسية:
               Age  DistanceFromHome (KM)    Education         Salary  \
count  1470.000000            1470.000000  1470.000000    1470.000000
mean     28.989796              22.502721     2.912925  112956.497959
std       7.993055              12.811124     1.024165  103342.889222
min      18.000000               1.000000     1.000000   20387.000000
25%      23.000000              12.000000     2.000000   43580.500000
50%      26.000000              22.000000     3.000000   71199.500000
75%      34.000000              33.000000     4.000000  142055.750000
max      51.000000              45.000000     5.000000  547204.000000

       StockOptionLevel  YearsAtCompany  YearsInMostRecentRole  \
count       1470.000000     1470.000000            1470.000000
mean           0.793878        4.562585               2.293197
std            0.852077        3.288048               2.539093
min            0.000000        0.000000               0.000000
25%            0.000000        2.000000               0.000000
50%            1.000000        4.000000               1.000000
75%            1.000000        7.000000               4.000000
max            3.000000       10.000000              10.000000

       YearsSinceLastPromotion  YearsWithCurrManager
count              1470.000000           1470.000000
mean                  3.440816              2.239456
std                   2.945194              2.505774
min                   0.000000              0.000000
25%                   1.000000              0.000000
50%                   3.000000              1.000000
75%                   6.000000              4.000000
max                  10.000000             10.000000

عدد القيم المفقودة في كل عمود:
EmployeeID                 0
FirstName                  0
LastName                   0
Gender                     0
Age                        0
BusinessTravel             0
Department                 0
DistanceFromHome (KM)      0
State                      0
Ethnicity                  0
Education                  0
EducationField             0
JobRole                    0
MaritalStatus              0
Salary                     0
StockOptionLevel           0
OverTime                   0
HireDate                   0
Attrition                  0
YearsAtCompany             0
YearsInMostRecentRole      0
YearsSinceLastPromotion    0
YearsWithCurrManager       0
dtype: int64

نسبة القيم المفقودة في كل عمود:
EmployeeID                 0.0
FirstName                  0.0
LastName                   0.0
Gender                     0.0
Age                        0.0
BusinessTravel             0.0
Department                 0.0
DistanceFromHome (KM)      0.0
State                      0.0
Ethnicity                  0.0
Education                  0.0
EducationField             0.0
JobRole                    0.0
MaritalStatus              0.0
Salary                     0.0
StockOptionLevel           0.0
OverTime                   0.0
HireDate                   0.0
Attrition                  0.0
YearsAtCompany             0.0
YearsInMostRecentRole      0.0
YearsSinceLastPromotion    0.0
YearsWithCurrManager       0.0
dtype: float64

عدد القيم المفقودة بعد المعالجة:
EmployeeID                 0
FirstName                  0
LastName                   0
Gender                     0
Age                        0
BusinessTravel             0
Department                 0
DistanceFromHome (KM)      0
State                      0
Ethnicity                  0
Education                  0
EducationField             0
JobRole                    0
MaritalStatus              0
Salary                     0
StockOptionLevel           0
OverTime                   0
HireDate                   0
Attrition                  0
YearsAtCompany             0
YearsInMostRecentRole      0
YearsSinceLastPromotion    0
YearsWithCurrManager       0
dtype: int64

عدد الصفوف المكررة بناءً على EmployeeID: 0
عدد الصفوف بعد حذف التكرارات: 1470

أنواع البيانات لكل عمود:
EmployeeID                 object
FirstName                  object
LastName                   object
Gender                     object
Age                         int64
BusinessTravel             object
Department                 object
DistanceFromHome (KM)       int64
State                      object
Ethnicity                  object
Education                   int64
EducationField             object
JobRole                    object
MaritalStatus              object
Salary                      int64
StockOptionLevel            int64
OverTime                   object
HireDate                   object
Attrition                  object
YearsAtCompany              int64
YearsInMostRecentRole       int64
YearsSinceLastPromotion     int64
YearsWithCurrManager        int64
dtype: object

أنواع البيانات بعد التحويل:
EmployeeID                         object
FirstName                          object
LastName                           object
Gender                             object
Age                                 int64
BusinessTravel                     object
Department                         object
DistanceFromHome (KM)               int64
State                              object
Ethnicity                          object
Education                           int64
EducationField                     object
JobRole                            object
MaritalStatus                      object
Salary                              int64
StockOptionLevel                    int64
OverTime                           object
HireDate                   datetime64[ns]
Attrition                          object
YearsAtCompany                      int64
YearsInMostRecentRole               int64
YearsSinceLastPromotion             int64
YearsWithCurrManager                int64
dtype: object

إحصائيات Age:
count    1470.000000
mean       28.989796
std         7.993055
min        18.000000
25%        23.000000
50%        26.000000
75%        34.000000
max        51.000000
Name: Age, dtype: float64
عدد القيم الشاذة في Age: 0

إحصائيات Salary:
count      1470.000000
mean     112956.497959
std      103342.889222
min       20387.000000
25%       43580.500000
50%       71199.500000
75%      142055.750000
max      547204.000000
Name: Salary, dtype: float64
عدد القيم الشاذة في Salary: 0

القيم الفريدة في Gender:
['Female' 'Male' 'Non-Binary' 'Prefer Not To Say']
القيم الفريدة في Gender بعد التنظيف:
['female' 'male' 'non-binary' 'prefer not to say']

القيم الفريدة في MaritalStatus:
['Divorced' 'Single' 'Married']
القيم الفريدة في MaritalStatus بعد التنظيف:
['divorced' 'single' 'married']

القيم الفريدة في Department:
['Sales' 'Human Resources' 'Technology']

القيم الفريدة في JobRole:
['Sales Executive' 'HR Business Partner' 'Engineering Manager' 'Recruiter'
 'Data Scientist' 'Machine Learning Engineer' 'Manager'
 'Software Engineer' 'Senior Software Engineer' 'Sales Representative'
 'Analytics Manager' 'HR Executive' 'HR Manager']

القيم الفريدة في Education:
[5 4 3 2 1]

تم حفظ الجدول بعد التنظيف باسم employee_cleaned.csv

In [11]:
satisfaction_levels = pd.DataFrame({
    'SatisfactionID': [1, 2, 3, 4, 5],
    'SatisfactionLevel': ['1 Very Dissatisfied', '2 Dissatisfied', '3 Neutral', '4 Satisfied', '5 Very Satisfied']
})
print("SatisfactionDim:")
print(satisfaction_levels.head())

rating_levels = pd.DataFrame({
    'RatingID': [1, 2, 3, 4, 5],
    'RatingLevel': ['1 Poor', '2 Fair', '3 Good', '4 Very Good', '5 Excellent']
})
print("\nRatingDim:")
print(rating_levels.head())

performance_rating_df['ReviewDate'] = pd.to_datetime(performance_rating_df['ReviewDate'])
dates = performance_rating_df['ReviewDate'].drop_duplicates().sort_values()
time_dim = pd.DataFrame({
    'TimeID': range(1, len(dates) + 1),
    'Date': dates,
    'Day': dates.dt.day,
    'Month': dates.dt.month,
    'Quarter': dates.dt.quarter,
    'Year': dates.dt.year
})
print("\nTimeDim:")
print(time_dim.head())

SatisfactionDim:
   SatisfactionID    SatisfactionLevel
0               1  1 Very Dissatisfied
1               2       2 Dissatisfied
2               3            3 Neutral
3               4          4 Satisfied
4               5     5 Very Satisfied

RatingDim:
   RatingID  RatingLevel
0         1       1 Poor
1         2       2 Fair
2         3       3 Good
3         4  4 Very Good
4         5  5 Excellent

TimeDim:
   TimeID       Date  Day  Month  Quarter  Year
0       1 2013-01-02    2      1        1  2013
1       2 2013-01-03    3      1        1  2013
3       3 2013-01-04    4      1        1  2013
6       4 2013-01-08    8      1        1  2013
7       5 2013-01-10   10      1        1  2013

In [12]:
employee_dim = employee_df.copy()

employee_dim = employee_dim[[
    'EmployeeID', 'FirstName', 'LastName', 'Gender', 'Age', 'BusinessTravel', 
    'DistanceFromHome (KM)', 'State', 'Ethnicity', 'Education', 'MaritalStatus', 
    'Salary', 'StockOptionLevel', 'OverTime', 'HireDate', 'Attrition', 
    'YearsAtCompany', 'YearsInMostRecentRole', 'YearsSinceLastPromotion', 
    'YearsWithCurrManager', 'Department', 'JobRole'
]]

employee_dim.columns = [
    'EmployeeID', 'FirstName', 'LastName', 'Gender', 'Age', 'BusinessTravel', 
    'DistanceFromHome', 'State', 'Ethnicity', 'Education', 'MaritalStatus', 
    'Salary', 'StockOptionLevel', 'OverTime', 'HireDate', 'Attrition', 
    'YearsAtCompany', 'YearsInMostRecentRole', 'YearsSinceLastPromotion', 
    'YearsWithCurrManager', 'Department', 'JobRole'
]

print("EmployeeDim:")
print(employee_dim.head())

EmployeeDim:
  EmployeeID   FirstName LastName      Gender  Age BusinessTravel  \
0  3012-1A41    Leonelle    Simco      female   30    Some Travel
1  CBCB-9C9D     Leonerd    Aland        male   38    Some Travel
2  95D7-1CE9       Ahmed    Sykes        male   43    Some Travel
3  47A0-559B  Ermentrude   Berrie  non-binary   39    Some Travel
4  42CC-040A       Stace   Savege      female   29    Some Travel

   DistanceFromHome State                Ethnicity  Education  ...  \
0                27    IL                    White          5  ...
1                23    CA                    White          4  ...
2                29    CA  Asian or Asian American          4  ...
3                12    IL                    White          3  ...
4                29    CA                    White          2  ...

  StockOptionLevel  OverTime   HireDate Attrition YearsAtCompany  \
0                1        No 2012-01-03        No             10
1                0       Yes 2012-01-04        No             10
2                1        No 2012-01-04        No             10
3                0        No 2012-01-05        No             10
4                0        No 2012-01-05       Yes              6

  YearsInMostRecentRole  YearsSinceLastPromotion  YearsWithCurrManager  \
0                     4                        9                     7
1                     6                       10                     0
2                     6                       10                     8
3                    10                       10                     0
4                     1                        1                     6

        Department              JobRole
0            sales      sales executive
1            sales      sales executive
2  human resources  hr business partner
3       technology  engineering manager
4  human resources            recruiter

[5 rows x 22 columns]

In [13]:
performance_rating_fact = performance_rating_df.copy()

performance_rating_fact['ReviewDate'] = pd.to_datetime(performance_rating_fact['ReviewDate'])
performance_rating_fact = performance_rating_fact.merge(
    time_dim[['TimeID', 'Date']], 
    left_on='ReviewDate', 
    right_on='Date', 
    how='left'
)
performance_rating_fact = performance_rating_fact.drop(columns=['ReviewDate', 'Date'])

performance_rating_fact = performance_rating_fact.merge(
    satisfaction_levels, 
    left_on='EnvironmentSatisfaction', 
    right_on='SatisfactionID', 
    how='left'
)
performance_rating_fact = performance_rating_fact.drop(columns=['EnvironmentSatisfaction', 'SatisfactionLevel'])
performance_rating_fact.rename(columns={'SatisfactionID': 'EnvironmentSatisfactionID'}, inplace=True)

performance_rating_fact = performance_rating_fact.merge(
    satisfaction_levels, 
    left_on='JobSatisfaction', 
    right_on='SatisfactionID', 
    how='left'
)
performance_rating_fact = performance_rating_fact.drop(columns=['JobSatisfaction', 'SatisfactionLevel'])
performance_rating_fact.rename(columns={'SatisfactionID': 'JobSatisfactionID'}, inplace=True)

performance_rating_fact = performance_rating_fact.merge(
    satisfaction_levels, 
    left_on='RelationshipSatisfaction', 
    right_on='SatisfactionID', 
    how='left'
)
performance_rating_fact = performance_rating_fact.drop(columns=['RelationshipSatisfaction', 'SatisfactionLevel'])
performance_rating_fact.rename(columns={'SatisfactionID': 'RelationshipSatisfactionID'}, inplace=True)

performance_rating_fact = performance_rating_fact.merge(
    satisfaction_levels, 
    left_on='WorkLifeBalance', 
    right_on='SatisfactionID', 
    how='left'
)
performance_rating_fact = performance_rating_fact.drop(columns=['WorkLifeBalance', 'SatisfactionLevel'])
performance_rating_fact.rename(columns={'SatisfactionID': 'WorkLifeBalanceID'}, inplace=True)

performance_rating_fact = performance_rating_fact.merge(
    rating_levels, 
    left_on='SelfRating', 
    right_on='RatingID', 
    how='left'
)
performance_rating_fact = performance_rating_fact.drop(columns=['SelfRating', 'RatingLevel'])
performance_rating_fact.rename(columns={'RatingID': 'SelfRatingID'}, inplace=True)

performance_rating_fact = performance_rating_fact[[
    'PerformanceID', 'EmployeeID', 'TimeID', 'EnvironmentSatisfactionID', 
    'JobSatisfactionID', 'RelationshipSatisfactionID', 'WorkLifeBalanceID', 
    'SelfRatingID', 'TrainingOpportunitiesWithinYear', 'TrainingOpportunitiesTaken'
]]

print("PerformanceRatingFact:")
print(performance_rating_fact.head())

PerformanceRatingFact:
  PerformanceID EmployeeID  TimeID  EnvironmentSatisfactionID  \
0          PR01  79F7-78EC       1                          5
1          PR02  B61E-0F26       2                          5
2          PR03  F5E3-48BB       2                          3
3          PR04  0678-748A       3                          5
4          PR05  541F-3E19       3                          5

   JobSatisfactionID  RelationshipSatisfactionID  WorkLifeBalanceID  \
0                  4                           5                  4
1                  4                           4                  4
2                  4                           5                  3
3                  3                           2                  2
4                  2                           3                  4

   SelfRatingID  TrainingOpportunitiesWithinYear  TrainingOpportunitiesTaken
0             4                                1                           0
1             4                                1                           3
2             5                                3                           2
3             3                                2                           0
4             4                                1                           0

In [14]:
employee_dim.to_csv('employee_dim.csv', index=False)
satisfaction_levels.to_csv('satisfaction_dim.csv', index=False)
rating_levels.to_csv('rating_dim.csv', index=False)
time_dim.to_csv('time_dim.csv', index=False)
performance_rating_fact.to_csv('performance_rating_fact.csv', index=False)

print("All tables have been saved as CSV files.")

All tables have been saved as CSV files.

In [1]:
from graphviz import Digraph

dot = Digraph(comment='Star Schema', format='png')
dot.attr(rankdir='TB') 
dot.node('PerformanceRatingFact', '''PerformanceRatingFact
PerformanceID (PK)
EmployeeID (FK)
TimeID (FK)
EnvironmentSatisfactionID (FK)
JobSatisfactionID (FK)
RelationshipSatisfactionID (FK)
WorkLifeBalanceID (FK)
SelfRatingID (FK)
TrainingOpportunitiesWithinYear
TrainingOpportunitiesTaken''', shape='box', style='filled', fillcolor='lightcoral')

dot.node('EmployeeDim', '''EmployeeDim
EmployeeID (PK)
FirstName
LastName
Gender
Age
BusinessTravel
DistanceFromHome
State
Ethnicity
Education
MaritalStatus
Salary
StockOptionLevel
OverTime
HireDate
Attrition
YearsAtCompany
YearsInMostRecentRole
YearsSinceLastPromotion
YearsWithCurrManager
Department
JobRole''', shape='box', style='filled', fillcolor='lightyellow')

dot.node('SatisfactionDim', '''SatisfactionDim
SatisfactionID (PK)
SatisfactionLevel''', shape='box', style='filled', fillcolor='lightyellow')

dot.node('RatingDim', '''RatingDim
RatingID (PK)
RatingLevel''', shape='box', style='filled', fillcolor='lightyellow')

dot.node('TimeDim', '''TimeDim
TimeID (PK)
Date
Day
Month
Quarter
Year''', shape='box', style='filled', fillcolor='lightyellow')

dot.edge('PerformanceRatingFact', 'EmployeeDim', label='EmployeeID', color='blue')
dot.edge('PerformanceRatingFact', 'TimeDim', label='TimeID', color='blue')
dot.edge('PerformanceRatingFact', 'SatisfactionDim', label='EnvironmentSatisfactionID', color='blue')
dot.edge('PerformanceRatingFact', 'SatisfactionDim', label='JobSatisfactionID', color='blue')
dot.edge('PerformanceRatingFact', 'SatisfactionDim', label='RelationshipSatisfactionID', color='blue')
dot.edge('PerformanceRatingFact', 'SatisfactionDim', label='WorkLifeBalanceID', color='blue')
dot.edge('PerformanceRatingFact', 'RatingDim', label='SelfRatingID', color='blue')

dot.render('star_schema_updated', view=True)

'star_schema_updated.png'

In [17]:
import os
print(os.getcwd())

C:\Users\dell

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import mysql.connector
from sqlalchemy import create_engine

In [5]:
import matplotlib
print(matplotlib.__version__)

3.10.1